### PR TITLE
Provide a min version for sodium

### PR DESCRIPTION
**Pull request by cryptonote-social**
The version of libsodium on Ubuntu 16 (1.0.8) is not compatible. I verified it works with 1.0.16.   It's possible it works with an even older version.

### CODE REVIEW

**Comment by cryptonote-social** [comment]
This is the error you get with 1.0.8:

`[100%] Linking CXX executable httpserver
../crypto/libcrypto.a(lokid_key.cpp.o): In function loki::calcPublicKey(std::array<unsigned char, 32ul> const&):
lokid_key.cpp:(.text+0x22): undefined reference to ge25519_scalarmult_base
lokid_key.cpp:(.text+0x2d): undefined reference to ge25519_p3_tobytes
`
